# File Name: audit.py
# Purpose: Defines the application-facing persistence and audit models for workflow run traceability.
# Creation Date: 2026-09-15
# Author: K.Kashiwagi

import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

# =====================================================================
# AUDIT EVENT CATEGORY
# Purpose:
# Lists the distinct kinds of workflow activity an audit event can
# record.
#
# Why:
# A fixed, small set of categories -- one per architectural concern
# already in this project (the workflow itself, the healthcare
# integration, a deterministic rule, AI, human review, or persistence)
# -- keeps audit records easy to filter and query later, without
# inventing categories nobody needs yet.
#
# Important Notes:
# - These values match the canonical event_categories reference table
#   (docs/database/reference_data.md Section 10), resolved in
#   docs/database/migration_plan.md Section 7.B: no generic ERROR
#   category exists. A failure is still recorded under its functional
#   domain (e.g. an AI failure is AI, not ERROR); the specific failure
#   classification belongs in failure_category_code, not here.
# =====================================================================


class AuditEventCategory(str, Enum):
    WORKFLOW = "WORKFLOW"
    FHIR = "FHIR"
    RULE = "RULE"
    AI = "AI"
    HUMAN = "HUMAN"
    PERSISTENCE = "PERSISTENCE"


# =====================================================================
# WORKFLOW RUN SNAPSHOT
# Purpose:
# Represents the current state of one canonical workflow run, identified
# by trace_id, for persistence and later retrieval.
#
# Why:
# The workflow run's status must be traceable without persisting
# clinical content, FHIR payloads, or AI text -- that content already
# lives, transiently, in src/workflow/state.py during a run. This
# snapshot records the canonical Wave 2 workflow_runs shape (see
# docs/database/data_dictionary.md `workflow_runs`): identity, current
# status, ownership/routing, lifecycle timestamps, and the standard nine
# control fields.
#
# Important Notes:
# - This model intentionally has no clinical_notes, FHIR payload,
#   member_id, provider_id, or AI response field.
# - Every *_code field is a plain string referencing a controlled
#   reference-master code (e.g. workflow_statuses.workflow_status_code).
#   This model does not validate that the code actually exists in its
#   reference table -- reference-data loading is a separate, still-OPEN
#   concern (see docs/database/migration_plan.md Section 16), and no
#   FK-validation business logic is added here.
# - trace_id is application-generated (UUID4), per ADR-007 -- never
#   generated by this model, by SQL Server, or independently by more
#   than one place.
# - Timestamp Policy: every *_at_utc field is always UTC. This model
#   does not perform timezone conversion itself -- the caller is
#   responsible for supplying values already normalized to UTC.
# =====================================================================


class WorkflowRunSnapshot(BaseModel):
    """A persisted snapshot of one canonical workflow run's current state."""

    model_config = ConfigDict(extra="forbid")

    trace_id: str = Field(min_length=1)
    case_id: str = Field(min_length=1)
    workflow_definition_id: str = Field(min_length=1)
    workflow_status_code: str = Field(min_length=1)
    next_action_code: str | None = None
    human_review_required: bool
    failure_category_code: str | None = None
    processing_department_id: str | None = None
    processing_location_id: str | None = None
    initiated_by_component_code: str = Field(min_length=1)
    started_at_utc: datetime
    completed_at_utc: datetime | None = None
    schema_version: str = "1"
    metadata_json: str | None = None
    created_at_utc: datetime
    created_by: str = Field(min_length=1)
    updated_at_utc: datetime
    updated_by: str = Field(min_length=1)
    is_deleted: bool = False
    deleted_at_utc: datetime | None = None
    deleted_by: str | None = None
    delete_reason_code: str | None = None
    delete_reason_text: str | None = None


# =====================================================================
# AUDIT EVENT
# Purpose:
# Represents one small, structured fact about workflow activity -- a
# step that happened, at a point in time, for one trace. Matches the
# canonical Wave 2 audit_events shape (see
# docs/database/data_dictionary.md `audit_events`).
#
# Why:
# Audit events are the append-only trail behind a WorkflowRunSnapshot's
# current state: multiple events accumulate over time for the same
# trace_id, so a reviewer can see the sequence of what happened, not
# just where a case ended up.
#
# Important Notes:
# - No raw clinical text, FHIR payload, AI prompt/response text,
#   credentials, or approval/denial/medical-necessity field belongs
#   here -- only small structured metadata (see CLAUDE.md Security
#   Rules and Task 18A's data-minimization requirement).
# - event_id defaults to a freshly generated UUID4 string when not
#   supplied. A UUID carries no PHI/PII and needs no external
#   dependency, so this is a safe, simple default -- callers that need
#   a specific ID (e.g. for idempotency) may still supply their own.
# - workflow_step_id references workflow_definition_steps.workflow_step_id
#   (a stable, application-generated surrogate id), not a Python
#   LangGraph node name and not a free-text step description -- see
#   ADR-007. This model does not perform the LangGraph-node-to-step_code
#   translation itself; that mapping is separate application logic, not
#   yet implemented (see ADR-007's Consequences).
# - Append-only: this model has no updated_at_utc/updated_by/is_deleted/
#   deleted_* fields, matching audit_events' table-level design note
#   that it never supports update or delete.
# - Timestamp Policy: occurred_at_utc and created_at_utc are always UTC,
#   matching WorkflowRunSnapshot's timestamp fields.
# =====================================================================


class AuditEvent(BaseModel):
    """One append-only audit record for a single workflow trace."""

    model_config = ConfigDict(extra="forbid")

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()), min_length=1)
    trace_id: str = Field(min_length=1)
    case_id: str = Field(min_length=1)
    event_type_code: str = Field(min_length=1)
    event_category_code: AuditEventCategory
    workflow_status_code: str | None = None
    workflow_step_id: str | None = None
    source_component_code: str = Field(min_length=1)
    actor_type_code: str = Field(min_length=1)
    actor_identifier: str | None = None
    result_code: str = Field(min_length=1)
    failure_category_code: str | None = None
    reason_code: str | None = None
    related_event_id: str | None = None
    occurred_at_utc: datetime
    schema_version: str = "1"
    metadata_json: str | None = None
    created_at_utc: datetime
    created_by: str = Field(min_length=1)
